### PR TITLE
removing ! from gestureBinding.instance reference for flutter 3.0 support

### PR DESCRIPTION
**Pull request by thelukewalton**

### CODE REVIEW

**Comment by peer-f** [comment]
@malikwang Please have a look at this PR if you can. This warning is getting really annoying. Thanks!

**Comment by malikwang** [comment]
> @malikwang Please have a look at this PR if you can. This warning is getting really annoying. Thanks!

OK, I will update this plugin.

**Comment by peer-f** [comment]
Thank you so much!

**Comment by malikwang** [comment]
@peer-f Version 1.1.1 has published

**Pull request merged**
